## Specify the Knowledge Base to use

In [1]:
import kmds
from kmds.tagging.tag_types import DataRepresentationTags
from owlready2 import *
from kmds.utils.load_utils import *
from kmds.utils.path_utils import get_package_kb_path
KNOWLEDGE_BASE = "../../src/kmds/examples/example_ml_kb_exp_workflow.xml"
onto2 :Ontology = load_kb(KNOWLEDGE_BASE)
import pandas as pd
pd.options.display.max_colwidth = 500

* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation

## Load the Exploratory Observations

In [2]:
load_exp_observations(onto2)

,obs_type,intent,finding,finding_seq
0,Data Quality Observation,DATA_UNDERSTANDING,"Customer ID, Description and Stock Code have null values",2
1,Relevance Observation,DATA_UNDERSTANDING,"For this task, the period considered is first quarter of 2010, other data are not relevant for this report",6
2,Data Quality Observation,DATA_UNDERSTANDING,"Some Prices are not numbers, these correspond to transactions that are some kind of adjustment - like returns, or,denoting some kind of payment adjustment.",4
3,Data Quality Observation,DATA_UNDERSTANDING,"Some products are not valid products. For example, some of these products seem to be created by software testers",5
4,Data Quality Observation,DATA_UNDERSTANDING,"Quantity, Price and Customer ID attributes have mixed types",1
5,Data Quality Observation,DATA_UNDERSTANDING,Some Quantities are not numbers,3

## Load the Data Representation Observations

In [3]:
load_data_rep_observations(onto2)

,obs_type,intent,finding,finding_seq
0,Data Transformation Observation,DATA_UNDERSTANDING,This data is from https://archive.ics.uci.edu/dataset/352/online+retail.The subset of transactions that fall in the first quarter of 2010 is filtered.Then the revenue for each product is computed. This is the data represenation for this example.,1

## Load the Modelling Choice Observations

In [4]:
load_modelling_choice_observations(onto2)

,obs_type,finding,finding_seq
0,Modelling Choice Observation,"contribution of products towards quaterly revenue shows a power law like behavior andso to facilitate understanding of the products that go significantly towards the generated quaterlyrevenue, we drop the products that materially do not contribute towards the revenue andsimply add dimensionality to the problem. Specifically, only 732 products out of a total of 3092 products,contribute to 80 percent of the revenue. Data analysis techniques such as PCA may be useful in reducing this732 to a sm...",1

## Load the Model Selection Observations

In [5]:
load_model_selection_observations(onto2)

,obs_type,intent,finding,finding_seq
0,Model Selection Statement,MODEL_SELECTION,"\nTo interpret PCA results for store inventory, analyze the 'loadings' (the coefficients of the original variables) for each principal component. These are stored in the `.components_` attribute of a fitted scikit-learn PCA object.\n\nThe core workflow is as follows:\n\n1. **Create a Loadings DataFrame**: Convert the `pca.components_` numpy array into a pandas DataFrame for easier analysis. The columns should be the original features (inventory items) and the index should be the principal c...",1

In [7]:
df_consolidated = load_observations(onto2)

In [8]:
fp = "../../src/kmds/examples/example_ml_kb_summary.txt"
df_consolidated.to_csv(fp, index=False)